### ISSUE TITLE
Proliferate this app across all adapters

### ISSUE THREAD

**Issue by leecalcote** [layer5io/learn-layer5#12]
**Desired Behavior**
All Meshery adapters should support the deployment of "learn-layer5".

**Comment by devansh42** [comment]
Hi! @leecalcote, I'm new to the community, Can you explain this issue further?

**Comment by leecalcote** [comment]
Hi @devansh42, thanks for asking. This issue is currently poorly described. It's a Golang-centric enhancement to be completed inside of each of Meshery's adapters. I'll mark this one postponed until we can get it better described and queued for implementation. In the meantime, please do have a look through these others: https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by leecalcote** [comment]
Assuming that you've already joined the community Slack (if not, here you go: https://slack.layer5.io), I encourage you to have a look at this issue - https://layer5io.slack.com/archives/CDM0ACDM5/p1625170999377600

**Comment by AugustasV** [comment]
That sample app could be added to the list of sample apps that are available when as users signed into the Local Provider. There is a simple script/list of manifests that get loaded on Meshery Server start that this can be added to.
