### ISSUE TITLE
[Docs] Include instructions on signing commits in the CONTRIBUTING.md

### ISSUE THREAD

**Issue by leecalcote** [layer5io/learn-layer5#21]
**Current Behavior**
The [CONTRIBUTING.md](https://github.com/layer5io/learn-layer5/blob/master/CONTRIBUTING.md) in this repo is missing an explanation and instructions on signing off on commits.

**Desired Behavior**
A copy of the same instructions from the Meshery repo's CONTRIBUTING.md's [section on signing commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) should be placed in into this repo's contributing instructions.

We will need to copy over the screenshots as well, which can be placed into the `readme` folder here - https://github.com/layer5io/learn-layer5/tree/master/img/readme

**Comment by Jashpatel1** [comment]
This repo dosen't contain CONTRIBUTING.md . So is it to be included in README.md or to create a new CONTRIBUTING.md.

**Comment by leecalcote** [comment]
@Jashpatel1 thanks for confirming. You're right - let's create a new CONTRIBUTING.md file here.

**Comment by Jashpatel1** [comment]
@leecalcote Is it something i can help with?

**Comment by leecalcote** [comment]
@Jashpatel1 yes, that would be excellent. Thank you.

**Comment by Jashpatel1** [comment]
@leecalcote I don't know more of what the file content should be, So do i include the details of signing of commit as of now.

**Comment by leecalcote** [comment]
@Jashpatel1 good point. Yes, I suppose for now just having the commit signing section will suffice. 

Long-term, we'll want to centralize the contributing instructions into one place for all repos to reference.
