### ISSUE TITLE
Update reserved network port

### ISSUE THREAD

**Issue by leecalcote** [layer5io/learn-layer5#54]
**Current Behavior**
This line identifies the reserved port number that this adapter is be listening on - https://github.com/layer5io/learn-layer5/blob/master/smi-conformance/main.go#L16. Currently, it is using port 10008. This needs to be changed to 10011.

**Implementation**
- [ ] Update `main.go` in this repo so that the adapter listens on the specific port reserved for it, which is port 10011. 
- [x] Update [Meshery Docs](https://github.com/layer5io/meshery/tree/master/docs) so that the reserved network port documentation reflects use of port 10011- https://meshery.layer5.io/docs/architecture#network-ports

**Comment by leecalcote** [comment]
@crustyy over here!

**Comment by leecalcote** [comment]
The second task is being completed here - https://github.com/layer5io/meshery/issues/1543

**Comment by KarenEfereyan** [comment]
Yes 😋😋😋 but @crustyy we Can work together
