### ISSUE TITLE
Update reference to gokit package dependency

### ISSUE THREAD

**Issue by leecalcote** [layer5io/learn-layer5#55]
**Description**
This [gokit package](https://github.com/layer5io/learn-layer5/blob/master/smi-conformance/main.go#L8) is being imported from `kumarabd`.

**Expected Behavior**
The gokit package should be imported from `layer5io`

**Implementation**
After changing the location of the package import, build the project to ensure it compiles correctly (no issues with new package reference)

**Comment by geraldmaboshe** [comment]
Hey @leecalcote  I'm interested in this
