### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/learn-layer5#91]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**Resources**

**Alternatives / Additional Context**

**Comment by depleur** [comment]
I can fix this issue.

**Comment by abhijeetgauravm** [comment]
Can u assign me? @thisiskaransgit

**Comment by abhijeetgauravm** [comment]
I want to work on it @thisiskaransgit . Can u assign me?

**Comment by rj2704** [comment]
You can assign this to me. I can fix this issue.

**Comment by Ghat0tkach** [comment]
There you go , @rj2704
