### ISSUE TITLE
[Documentation] update the CONTRIBUTING.md with Issues & Pull Requests sections

### ISSUE THREAD

**Issue by sandramsc** [layer5io/learn-layer5#93]
Link to issue: [learn-layer5](https://github.com/layer5io/layer5/issues/4932)

**Comment by sandramsc** [comment]
Hi, _(only if there's a need to do so in this case)_ can I have this issue assigned to me, please?

- currently working on this issue in the Layer5 repo, creating a new issue in each repo mentioned so as to effectively maintain the procedure of creating an issue and thereafter a PR that closes it.

**Comment by thakuraman24** [comment]
@saurabh100ni I am just a novice to this open source contribution, and I have heard that documentation is the place to start with so can I have this issue assigned to me also please, I would try my very best to update the documentation.

**Comment by saurabh100ni** [comment]
hey @thakuraman24 Welcome to the community 🚀
as @sandramsc is already working on that you can go for other issues. 
Go @thakuraman24 and make impact 😎🚀

**Comment by abhijeetgauravm** [comment]
> @saurabh100ni I am just a novice to this open source contribution, and I have heard that documentation is the place to start with so can I have this issue assigned to me also please, I would try my very best to update the documentation.

hey @thakuraman24 we do have a bunch of good first issues open, you are most welcome to contribute!
